# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Maia
title: Technical Projects Systems Engineer
email: maia.ruben@gmail.com
website: rbnmaia.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rb3n0s
github_username:  rbnmaia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username:
linkedin_username: rbnmaia
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/picture.png
about_content: |
  Hi, my name's Ruben and I'm a technical projects systems engineer. As well as implementing and configuring systems I also have experience making software and agile.

  I build content oriented to Security Solutions for demo purposes to help pre and post sales teams as well as any of our partners to upskill within those labs.

  From my studies I transitioned to the field the passion for CyberSecurity and Forensics, which I try to keep up in my free time still pursuing OSCP.

  I am most skilled in: <mark>Network Security</mark> , <mark>CyberSecurity</mark> and <mark>Virtualization</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Purple Pages
        link: ruben-maia.gitbook.io/purplelists/
        # link_text: Project Website
        additional_links:
          - title: netsec-docs
            icon: fab fa-github
            url: https://github.com/rbnmaia/netsec-docs
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
          This project is a living project to reflect a journey in penetration testing.
        description: |
          Purple Lists are a source of information to help individuals to be proficient in offensive security by providing a set of examples for each phase of a penetration test engagement.

          With Purple Lists, you can set as a reference "framework" to follow while you practice your skill-set and tune it as you go, without the need of memorizing dozens of commands (over time your brain will mechanize it).

          Either you are on the field or just starting, you will find some great notes to get you started.
      
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Cisco Systems, Inc.
        link:
        # link_text:
        sub_title: Technical Projects Systems Engineer
        caption: 2021 - Present
        quote: >
          GDE Security Practice - Poland
        description: |
          - Design, build and implement to stakeholders specifications demo labs for Cisco Secure Portfolio.
          - Proposed technical feasibility solutions for new system designs and suggested options for performance improvement of technical components.
          - Documented system configuration, mapping and processes.
          - Supported system users, educating employees on troubleshooting and problem-solving protocols.
          - Conducted end-user reviews for modified and new systems.
          - Suggested system updates or changes after conduct in-depth technical reviews.
          - Optimized networked software and operating systems by applying updates and patches.
          - Handled scripting tasks for debugging and automation using Python.
          - Checked for accuracy and functionality during implementation of new systems.
      - layout: left
        title: Cisco Systems, Inc.
        link:
        # link_text:
        sub_title: Customer Success Specialist
        caption: 2019 - 2021
        quote: >
          Customer Support Specialist responsibilities include resolving customer queries, recommending solutions and guiding product users through features and functionalities.
        description: |
          - Focused on supporting Cisco Security Portfolio: Cisco Identity Services Engine (ISE), Secure Network Analytics & Cloud Anayltics (SWE & SWC), Secure Endpoint (AMP4E), Secure Malware Analytics (TG), SecureX Threat Response (CTR), SecureX, Global Threat Alerts (CTA).
          - Piloted projects for Healthchecks in AMP and ISE, helping SOC teams to create workflows.
          - Provided proactive advice, support, guidance and education to customers on Threat Hunting and Incident Response.
          - Interacting and planning solutions across teams and theaters on multicultural environments.
          - Content creation for all referred technologies, process automation and lab environment guidance.
          - Mentoring of new graduates and new hires.
          - Global SME for Secure Endpoint in EMEAR and previously Regional SME for Identity Services Engine in EMEAR.
          - Driving adoption around Cisco Security Portfolio and SecureX Orchestration and automation, explaining workflows and the programmability required.
      - layout: left
        title: HSBC
        link:
        # link_text:
        sub_title: Application Production Support Specialist
        caption: 2019 - 2019
        quote: >
          An application specialist is responsible for the support and maintenance of application systems that are critical to the daily operations of the firm. 
        description: |
          - BMC Control-M, Qlik View/Sense, PL/SQL, SPLUNK / AppDynamics (monitoring)
          - Automation, analytics, database control and SIEM monitoring
          - Responsible for changes and maintenance windows on critical systems.
          - Responded to support requests from end users on data access and authorization.
          - Handled incidents on critical systems responsible for credit payment decisions and anti-fraud.
          - Maintaining infrastructure and documentation Wiki (confluence).
      - layout: left
        title: Cisco Systems, Inc.
        link:
        # link_text:
        sub_title: Technical Support Engineer
        caption: 2016 - 2018
        quote: >
           A Technical Support Engineer is responsible for providing technical support to clients in person and remotely. Giving such assistance means that it's all about solving problems from the moment they call the customer service line until the caller's issues are resolved. 
        description: |
          - AAA

  - title: Education
    layout: list
    content:
      - layout: left
        title: Polytechnic Institute of Leiria
        caption: 2015 - 2018
        sub_title: MSc. Mobile Computing
        quote: >
          The aim of this master's degree is to confer a professional specialization with great emphasis on mobile computing and related technologies, allowing a series of studies to the holders of a degree in Computer Engineering, and related courses, including the possibility of expertise to professionals in the labour market
        description: |
          Masters in Mobile Computing / Mobile Forensics / Thesis in IOT Security
        
      - layout: left
        title: Polytechnic Institute of Leiria
        caption: 2010 - 2015
        sub_title: BSc. Computer Engineering
        quote: >
          The degree in Computer Engineering aims to train professionals with skills in the areas of Information Systems and Information and Communication Technologies.
        description: |
          Bachelor in Computer Engineering / Software and Networks / Final Project in Android
  
  - title: Certifications
    layout: text
    content: |
      Alongside my job, I took time to certify myself into:
      - CCNP Security
      - CCNA CyberOps
      - DevNet Associate
        
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - CTFs
            THM profile: https://tryhackme.com/p/rb3n0s
            CTF time: https://ctftime.org/team/134736
      - 80s/90s Action Movies/Series
      - Retro Computing/Gaming
      - Darts/Billiards
      - Whiskey tasting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
