# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ruben Maia
title: Technical Projects Systems Engineer
email: maia.ruben@gmail.com
website: rbnmaia.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rb3n0s
github_username:  rbnmaia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username:
linkedin_username: rbnmaia
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Ruben and I'm a technical projects systems engineer. As well as administrating systems I also have experience making software and web apps.

  I am most skilled in: <mark>Network Security</mark> and <mark>Brainstorming</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Purple Pages
        link: ruben-maia.gitbook.io/purplelists/
        # link_text: Project Website
        additional_links:
          - title: netsec-docs
            icon: fab fa-github
            url: https://github.com/rbnmaia/netsec-docs
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
          This project is a living project to reflect a journey in penetration testing.
        description: |
          Purple Lists are a source of information to help individuals to be proficient in offensive security by providing a set of examples for each phase of a penetration test engagement.

          With Purple Lists, you can set as a reference "framework" to follow while you practice your skill-set and tune it as you go, without the need of memorizing dozens of commands (over time your brain will mechanize it).

          Either you are on the field or just starting, you will find some great notes to get you started.
      
  - title: Experience
    layout: list
    content:
      - layout: left
        title:
        link:
        # link_text:
        sub_title:
        caption:
        quote: >
        
        description: |
      - layout: left
        title:
        link:
        # link_text:
        sub_title:
        caption:
        quote: >
        
        description: |
      - layout: left
        title:
        link:
        # link_text:
        sub_title:
        caption:
        quote: >
        
        description: |

  - title: Education
    layout: list
    content:
      - layout: left
        title:
        caption:
        sub_title:
        quote: >
        
        description: | 
        
      - layout: left
        title:
        caption:
        sub_title:
        quote: >
        
        description: |
  
  - title: Certifications
    layout: list
    content:
      - layout: left
        title:
        caption:
        sub_title:
        quote: >
        
        description: |
        
      - layout: left
        title:
        caption:
        sub_title:
        quote: >
        
        description: |

     - layout: left
        title:
        caption:
        sub_title:
        quote: >
        
        description: |

        
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Billiards
      - Gaming
      - Darts
      - Whiskey tasting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
